### ISSUE TITLE
Eliminate unused stack items

### ISSUE THREAD

**Issue by maxgillett** [delendum-xyz/valida-compiler#5]
When we merge gMIR instructions that have consecutive loads and stores, we sometimes end up with dead stack items that are no longer used by the function. We need to write an optimization pass that walks over `MachineFunction` and uses `MachineFrameInfo` to identify and remove dead stack slots. We then need update instructions that refer to stack items with the new resulting offsets.

**Comment by vivekvpandya** [comment]
not sure if this really requires a new Pass. There seems to be similar pass https://github.com/llvm/llvm-project/blob/main/llvm/lib/CodeGen/LiveStacks.cpp
It may be possible to improve this pass or clean up based on this pass is not getting triggered some how?

**Comment by maxgillett** [comment]
Fixed in 22c08a3672c22626a2152b52925e516ae338e85f
